"""Governed quantitative-research workflows."""

from alphaforge.research.artifacts import (
    TABLE_ARTIFACT_FORMAT,
    TABLE_ARTIFACT_VERSION,
    ArtifactValidationError,
    read_frame_artifact,
    write_frame_artifact,
)
from alphaforge.research.baseline_study import (
    NAIVE_CANDIDATE,
    SPRINT_2_CANDIDATES,
    BaselineStudyResult,
    run_governed_baseline_study,
)
from alphaforge.research.deep_sequence_study import (
    DEEP_SEQUENCE_CANDIDATES,
    DeepSequenceStudyConfig,
    DeepSequenceStudyResult,
    load_deep_sequence_study_config,
    run_deep_sequence_study,
)
from alphaforge.research.governance import (
    GOVERNANCE_SCHEMA_VERSION,
    HEAD_FILE_NAME,
    LEDGER_FILE_NAME,
    ROOT_TRIAL_ID,
    DuplicateTrialError,
    FamilyEvaluation,
    FrozenResearchPlan,
    IncompleteTrialFamilyError,
    KillCriterion,
    LedgerIntegrityError,
    MultipleTestingPolicy,
    ResearchGovernanceError,
    ResearchLedger,
    TrialSpec,
    adjust_p_values,
)
from alphaforge.research.manifest import (
    ExperimentManifest,
    ManifestValidationError,
    capture_environment,
    capture_git_context,
    derive_seed_map,
    inventory_artifacts,
    redact_cli_arguments,
    refresh_experiment_manifest,
    write_experiment_manifest,
)
from alphaforge.research.signal_foundry import (
    GovernedResearchConfig,
    GovernedResearchResult,
    run_governed_signal_foundry_research,
)
from alphaforge.research.time_frequency_study import (
    TIME_FREQUENCY_CANDIDATES,
    TimeFrequencyStudyConfig,
    TimeFrequencyStudyResult,
    build_synthetic_time_frequency_reference,
    load_time_frequency_study_config,
    run_synthetic_time_frequency_study,
    run_time_frequency_study,
)

__all__ = [
    "TABLE_ARTIFACT_FORMAT",
    "TABLE_ARTIFACT_VERSION",
    "ArtifactValidationError",
    "BaselineStudyResult",
    "DEEP_SEQUENCE_CANDIDATES",
    "DeepSequenceStudyConfig",
    "DeepSequenceStudyResult",
    "DuplicateTrialError",
    "ExperimentManifest",
    "FamilyEvaluation",
    "FrozenResearchPlan",
    "GOVERNANCE_SCHEMA_VERSION",
    "GovernedResearchConfig",
    "GovernedResearchResult",
    "HEAD_FILE_NAME",
    "IncompleteTrialFamilyError",
    "KillCriterion",
    "LEDGER_FILE_NAME",
    "LedgerIntegrityError",
    "ManifestValidationError",
    "MultipleTestingPolicy",
    "NAIVE_CANDIDATE",
    "ROOT_TRIAL_ID",
    "ResearchGovernanceError",
    "ResearchLedger",
    "SPRINT_2_CANDIDATES",
    "TrialSpec",
    "TIME_FREQUENCY_CANDIDATES",
    "TimeFrequencyStudyConfig",
    "TimeFrequencyStudyResult",
    "adjust_p_values",
    "capture_environment",
    "capture_git_context",
    "derive_seed_map",
    "inventory_artifacts",
    "build_synthetic_time_frequency_reference",
    "load_deep_sequence_study_config",
    "load_time_frequency_study_config",
    "read_frame_artifact",
    "refresh_experiment_manifest",
    "redact_cli_arguments",
    "run_governed_baseline_study",
    "run_governed_signal_foundry_research",
    "run_deep_sequence_study",
    "run_synthetic_time_frequency_study",
    "run_time_frequency_study",
    "write_experiment_manifest",
    "write_frame_artifact",
]
