"""Governed quantitative-research workflows."""

from alphaforge.research.artifacts import (
    TABLE_ARTIFACT_FORMAT,
    TABLE_ARTIFACT_VERSION,
    ArtifactValidationError,
    read_frame_artifact,
    write_frame_artifact,
)
from alphaforge.research.baseline_study import (
    NAIVE_CANDIDATE,
    SPRINT_2_CANDIDATES,
    BaselineStudyResult,
    run_governed_baseline_study,
)
from alphaforge.research.governance import (
    GOVERNANCE_SCHEMA_VERSION,
    HEAD_FILE_NAME,
    LEDGER_FILE_NAME,
    ROOT_TRIAL_ID,
    DuplicateTrialError,
    FamilyEvaluation,
    FrozenResearchPlan,
    IncompleteTrialFamilyError,
    KillCriterion,
    LedgerIntegrityError,
    MultipleTestingPolicy,
    ResearchGovernanceError,
    ResearchLedger,
    TrialSpec,
    adjust_p_values,
)
from alphaforge.research.manifest import (
    ExperimentManifest,
    ManifestValidationError,
    capture_environment,
    capture_git_context,
    derive_seed_map,
    inventory_artifacts,
    redact_cli_arguments,
    refresh_experiment_manifest,
    write_experiment_manifest,
)
from alphaforge.research.signal_foundry import (
    GovernedResearchConfig,
    GovernedResearchResult,
    run_governed_signal_foundry_research,
)

__all__ = [
    "TABLE_ARTIFACT_FORMAT",
    "TABLE_ARTIFACT_VERSION",
    "ArtifactValidationError",
    "BaselineStudyResult",
    "DuplicateTrialError",
    "ExperimentManifest",
    "FamilyEvaluation",
    "FrozenResearchPlan",
    "GOVERNANCE_SCHEMA_VERSION",
    "GovernedResearchConfig",
    "GovernedResearchResult",
    "HEAD_FILE_NAME",
    "IncompleteTrialFamilyError",
    "KillCriterion",
    "LEDGER_FILE_NAME",
    "LedgerIntegrityError",
    "ManifestValidationError",
    "MultipleTestingPolicy",
    "NAIVE_CANDIDATE",
    "ROOT_TRIAL_ID",
    "ResearchGovernanceError",
    "ResearchLedger",
    "SPRINT_2_CANDIDATES",
    "TrialSpec",
    "adjust_p_values",
    "capture_environment",
    "capture_git_context",
    "derive_seed_map",
    "inventory_artifacts",
    "read_frame_artifact",
    "refresh_experiment_manifest",
    "redact_cli_arguments",
    "run_governed_baseline_study",
    "run_governed_signal_foundry_research",
    "write_experiment_manifest",
    "write_frame_artifact",
]
